text=" hello, world!  "
print(text)
text_upper=text.upper()
print(text_upper)
text_stripped=text.strip()
print(text_stripped)
replace_text=text.replace("World","Python")
print(replace_text)
word_list=text.split(",")
print(word_list)
start_with_hello=text.startswith(" hello")
print(start_with_hello)
ends_with=text.endswith("!  ")
print(ends_with)
text="Python is awesome"
print(text)
sentence=text.split(" ")
print(sentence)
joined_text="-".join(text)
print(joined_text)
